spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.nvn4kcx.mongodb.net/helpdeskdb?retryWrites=true&w=majority'
      auto-index-creation: true
spring-doc:
  openapi:
    title: 'User Service API'
    description: 'Component responsible for User Management'
    version: '1.0.0'